export const GET_TICKETS_REQUEST = "GET_TICKETS_REQUEST"
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS"
export const GET_TICKETS_FAILURE = "GET_TICKETS_FAILURE"

export const GET_SEARCH_ID_REQUEST = "GET_SEARCH_ID_REQUEST"
export const GET_SEARCH_ID_SUCCESS = "GET_SEARCH_ID_SUCCESS"
export const GET_SEARCH_ID_FAILURE = "GET_SEARCH_ID_FAILURE"

export const GET_SELECTED_SORTER = "GET_SELECTED_SORTER"

export const TOGGLE_CHECKBOX = "TOGGLE_CHECKBOX"
export const TOGGLE_MAIN_CHECKBOX = "TOGGLE_MAIN_CHECKBOX"


